# 1. Video to Coordinates #

In [ ]:

from helpers.video_to_coord import process_video_fast

name = "cherrie"
VIDEO_PATH = "./data/cherrie.MOV"
MODEL_PATH = "./pose_landmarker_lite.task"

PROCESS_EVERY_N_FRAMES = 30
PROCESS_FIRST_N_SECONDS = None
SKIP_UNPROCESSED_FRAMES = True


detected_landmarks = process_video_fast(
    video_path=VIDEO_PATH,
    model_path=MODEL_PATH,
    process_every_n_frames=PROCESS_EVERY_N_FRAMES,
    process_first_n_seconds=PROCESS_FIRST_N_SECONDS,
)


from helpers.video_to_coord import landmarks_to_dataframe
df = landmarks_to_dataframe(detected_landmarks)
df

Video info:
  - FPS: 29
  - Resolution: 1080x1920
  - Total frames: 17528
  - Duration: 604.41 seconds
  - Processing full video
  - Processing every 30 frames (~585 frames will be analyzed)

,Frame,p11,p12,p13,p14,p15,p16,p23,p24,p25,p26,p27,p28
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60,"(0.664, 0.444, -0.199)","(0.538, 0.432, 0.165)","(0.674, 0.508, -0.360)","(0.426, 0.393, 0.161)","(0.648, 0.581, -0.485)","(0.330, 0.344, -0.013)","(0.591, 0.603, -0.113)","(0.521, 0.598, 0.113)","(0.577, 0.697, -0.236)","(0.522, 0.709, 0.095)","(0.572, 0.788, -0.061)","(0.541, 0.787, 0.425)"
3,90,"(0.667, 0.458, 0.004)","(0.524, 0.436, 0.103)","(0.672, 0.531, 0.014)","(0.429, 0.381, -0.078)","(0.660, 0.595, -0.078)","(0.356, 0.326, -0.315)","(0.604, 0.607, -0.016)","(0.521, 0.603, 0.016)","(0.589, 0.734, 0.008)","(0.522, 0.740, -0.017)","(0.574, 0.844, 0.116)","(0.497, 0.856, 0.063)"
4,120,"(0.603, 0.457, -0.043)","(0.460, 0.437, -0.091)","(0.607, 0.531, 0.085)","(0.369, 0.374, -0.287)","(0.606, 0.596, 0.059)","(0.302, 0.318, -0.481)","(0.565, 0.603, 0.022)","(0.479, 0.603, -0.023)","(0.592, 0.712, 0.092)","(0.475, 0.728, -0.014)","(0.619, 0.808, 0.286)","(0.491, 0.850, 0.115)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,17400,"(0.530, 0.444, 0.076)","(0.375, 0.444, 0.035)","(0.571, 0.520, -0.152)","(0.362, 0.525, -0.156)","(0.514, 0.472, -0.526)","(0.419, 0.472, -0.457)","(0.513, 0.590, -0.005)","(0.411, 0.595, 0.005)","(0.564, 0.695, 0.003)","(0.408, 0.727, -0.027)","(0.601, 0.790, 0.233)","(0.457, 0.828, 0.101)"
581,17430,"(0.523, 0.446, 0.077)","(0.365, 0.447, 0.037)","(0.567, 0.520, -0.145)","(0.358, 0.526, -0.168)","(0.504, 0.476, -0.522)","(0.413, 0.476, -0.503)","(0.505, 0.592, -0.013)","(0.406, 0.598, 0.013)","(0.474, 0.712, -0.015)","(0.400, 0.730, -0.013)","(0.518, 0.807, 0.234)","(0.449, 0.829, 0.159)"
582,17460,"(0.521, 0.447, 0.066)","(0.362, 0.449, 0.066)","(0.568, 0.520, -0.176)","(0.356, 0.530, -0.132)","(0.510, 0.475, -0.547)","(0.412, 0.480, -0.447)","(0.504, 0.590, -0.034)","(0.405, 0.597, 0.034)","(0.473, 0.710, -0.064)","(0.398, 0.730, -0.017)","(0.561, 0.804, 0.156)","(0.462, 0.832, 0.113)"
583,17490,"(0.526, 0.442, 0.043)","(0.364, 0.445, -0.038)","(0.569, 0.521, -0.173)","(0.362, 0.530, -0.240)","(0.506, 0.481, -0.583)","(0.425, 0.484, -0.569)","(0.515, 0.594, -0.002)","(0.412, 0.601, 0.002)","(0.532, 0.713, 0.031)","(0.404, 0.732, -0.011)","(0.560, 0.807, 0.309)","(0.449, 0.832, 0.210)"
584,17520,"(0.529, 0.444, 0.111)","(0.368, 0.444, -0.034)","(0.586, 0.521, -0.095)","(0.362, 0.527, -0.244)","(0.521, 0.481, -0.504)","(0.449, 0.484, -0.537)","(0.526, 0.596, 0.024)","(0.418, 0.602, -0.024)","(0.580, 0.715, 0.042)","(0.416, 0.736, -0.054)","(0.617, 0.812, 0.306)","(0.470, 0.842, 0.115)"

# 2. Process Coordinates --> Convert to Angles + Additional Features #

In [2]:
from helpers.calculated_feature import calculate_motion_features_df
# angle1	(11, 13, 15)	Left elbow
# angle2	(12, 14, 16)	Right elbow
# angle3	(11, 13, 23)	Left shoulder
# angle4	(12, 14, 24)	Right shoulder
# angle5	(11, 23, 25)	Left hip
# angle6	(12, 24, 26)	Right hip

feature_df = calculate_motion_features_df(
    df,
    fps=30,
    rom_window_seconds=1.0,
)
feature_df

,Frame,time_sec,angle_1_deg,angle_2_deg,angle_3_deg,angle_4_deg,angle_5_deg,angle_6_deg,angular_velocity_1_deg_per_s,angular_velocity_2_deg_per_s,...,vertex_speed_angle_6_p24_coord_per_s,rom_1s_angle_1_deg,rom_1s_angle_2_deg,rom_1s_angle_3_deg,rom_1s_angle_4_deg,rom_1s_angle_5_deg,rom_1s_angle_6_deg,symmetry_absdiff_angle_1_vs_2_deg,symmetry_absdiff_angle_3_vs_4_deg,symmetry_absdiff_angle_5_vs_6_deg
0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60.0,2.0,164.021046,123.369079,44.181805,47.711020,100.245778,169.808967,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,40.651967,3.529215,69.563189
3,90.0,3.0,116.330037,169.419731,128.695684,45.971520,156.082712,165.963855,-47.691009,46.050652,...,0.097129,47.691009,46.050652,84.513879,1.739500,55.836934,3.845111,53.089694,82.724164,9.881143
4,120.0,4.0,98.205633,174.281623,79.168880,22.520089,153.409185,160.233055,-18.124405,4.861891,...,0.057315,18.124405,4.861891,49.526804,23.451431,2.673527,5.730800,76.075990,56.648791,6.823870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,17400.0,580.0,148.514565,144.260453,43.485040,47.251849,134.711424,165.379642,1.525054,-2.060458,...,0.012369,1.525054,2.060458,13.958748,13.243384,9.059212,8.985057,4.254113,3.766809,30.668218
581,17430.0,581.0,147.969090,148.541761,46.404863,43.940903,148.662120,162.311315,-0.545476,4.281308,...,0.009899,0.545476,4.281308,2.919823,3.310947,13.950697,3.068327,0.572671,2.463960,13.649194
582,17460.0,582.0,149.489351,146.792047,42.706668,45.711899,157.714770,159.412908,1.520261,-1.749715,...,0.021048,1.520261,1.749715,3.698195,1.770996,9.052650,2.898407,2.697304,3.005231,1.698138
583,17490.0,583.0,148.000087,147.389677,42.328663,40.341920,145.970854,151.797334,-1.489264,0.597630,...,0.033000,1.489264,0.597630,0.378005,5.369980,11.743916,7.615574,0.610410,1.986744,5.826480
584,17520.0,584.0,145.042164,145.471299,50.371607,41.718953,135.075214,155.649150,-2.957923,-1.918378,...,0.026702,2.957923,1.918378,8.042944,1.377033,10.895641,3.851816,0.429135,8.652654,20.573937

# 3. Add in LDF and AMI#

In [3]:
from helpers.read_ldf import readLDFdata
LDF_bloodflow = readLDFdata("./data/angela")
if len(LDF_bloodflow) < len(feature_df):
    LDF_bloodflow.extend([None] * (len(feature_df) - len(LDF_bloodflow)))
elif len(LDF_bloodflow) > len(feature_df):
    LDF_bloodflow = LDF_bloodflow[:len(feature_df)]
feature_df['LDF_bloodflow'] = LDF_bloodflow
feature_df

,Frame,time_sec,angle_1_deg,angle_2_deg,angle_3_deg,angle_4_deg,angle_5_deg,angle_6_deg,angular_velocity_1_deg_per_s,angular_velocity_2_deg_per_s,...,rom_1s_angle_1_deg,rom_1s_angle_2_deg,rom_1s_angle_3_deg,rom_1s_angle_4_deg,rom_1s_angle_5_deg,rom_1s_angle_6_deg,symmetry_absdiff_angle_1_vs_2_deg,symmetry_absdiff_angle_3_vs_4_deg,symmetry_absdiff_angle_5_vs_6_deg,LDF_bloodflow
0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,329.4
1,30.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283.0
2,60.0,2.0,164.021046,123.369079,44.181805,47.711020,100.245778,169.808967,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,40.651967,3.529215,69.563189,281.7
3,90.0,3.0,116.330037,169.419731,128.695684,45.971520,156.082712,165.963855,-47.691009,46.050652,...,47.691009,46.050652,84.513879,1.739500,55.836934,3.845111,53.089694,82.724164,9.881143,281.8
4,120.0,4.0,98.205633,174.281623,79.168880,22.520089,153.409185,160.233055,-18.124405,4.861891,...,18.124405,4.861891,49.526804,23.451431,2.673527,5.730800,76.075990,56.648791,6.823870,371.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,17400.0,580.0,148.514565,144.260453,43.485040,47.251849,134.711424,165.379642,1.525054,-2.060458,...,1.525054,2.060458,13.958748,13.243384,9.059212,8.985057,4.254113,3.766809,30.668218,NaN
581,17430.0,581.0,147.969090,148.541761,46.404863,43.940903,148.662120,162.311315,-0.545476,4.281308,...,0.545476,4.281308,2.919823,3.310947,13.950697,3.068327,0.572671,2.463960,13.649194,NaN
582,17460.0,582.0,149.489351,146.792047,42.706668,45.711899,157.714770,159.412908,1.520261,-1.749715,...,1.520261,1.749715,3.698195,1.770996,9.052650,2.898407,2.697304,3.005231,1.698138,NaN
583,17490.0,583.0,148.000087,147.389677,42.328663,40.341920,145.970854,151.797334,-1.489264,0.597630,...,1.489264,0.597630,0.378005,5.369980,11.743916,7.615574,0.610410,1.986744,5.826480,NaN
584,17520.0,584.0,145.042164,145.471299,50.371607,41.718953,135.075214,155.649150,-2.957923,-1.918378,...,2.957923,1.918378,8.042944,1.377033,10.895641,3.851816,0.429135,8.652654,20.573937,NaN

In [4]:
from helpers.read_ami import readAMIdata
AMI_bloodflow = readAMIdata("./data/angela")
if len(AMI_bloodflow) < len(feature_df):
    AMI_bloodflow.extend([None] * (len(feature_df) - len(AMI_bloodflow)))
elif len(AMI_bloodflow) > len(feature_df):
    AMI_bloodflow = AMI_bloodflow[:len(feature_df)]
feature_df['AMI_bloodflow'] = AMI_bloodflow
feature_df

,Frame,time_sec,angle_1_deg,angle_2_deg,angle_3_deg,angle_4_deg,angle_5_deg,angle_6_deg,angular_velocity_1_deg_per_s,angular_velocity_2_deg_per_s,...,rom_1s_angle_2_deg,rom_1s_angle_3_deg,rom_1s_angle_4_deg,rom_1s_angle_5_deg,rom_1s_angle_6_deg,symmetry_absdiff_angle_1_vs_2_deg,symmetry_absdiff_angle_3_vs_4_deg,symmetry_absdiff_angle_5_vs_6_deg,LDF_bloodflow,AMI_bloodflow
0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,329.4,2882.0
1,30.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283.0,2856.0
2,60.0,2.0,164.021046,123.369079,44.181805,47.711020,100.245778,169.808967,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,40.651967,3.529215,69.563189,281.7,2927.0
3,90.0,3.0,116.330037,169.419731,128.695684,45.971520,156.082712,165.963855,-47.691009,46.050652,...,46.050652,84.513879,1.739500,55.836934,3.845111,53.089694,82.724164,9.881143,281.8,2883.0
4,120.0,4.0,98.205633,174.281623,79.168880,22.520089,153.409185,160.233055,-18.124405,4.861891,...,4.861891,49.526804,23.451431,2.673527,5.730800,76.075990,56.648791,6.823870,371.5,2902.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,17400.0,580.0,148.514565,144.260453,43.485040,47.251849,134.711424,165.379642,1.525054,-2.060458,...,2.060458,13.958748,13.243384,9.059212,8.985057,4.254113,3.766809,30.668218,NaN,NaN
581,17430.0,581.0,147.969090,148.541761,46.404863,43.940903,148.662120,162.311315,-0.545476,4.281308,...,4.281308,2.919823,3.310947,13.950697,3.068327,0.572671,2.463960,13.649194,NaN,NaN
582,17460.0,582.0,149.489351,146.792047,42.706668,45.711899,157.714770,159.412908,1.520261,-1.749715,...,1.749715,3.698195,1.770996,9.052650,2.898407,2.697304,3.005231,1.698138,NaN,NaN
583,17490.0,583.0,148.000087,147.389677,42.328663,40.341920,145.970854,151.797334,-1.489264,0.597630,...,0.597630,0.378005,5.369980,11.743916,7.615574,0.610410,1.986744,5.826480,NaN,NaN
584,17520.0,584.0,145.042164,145.471299,50.371607,41.718953,135.075214,155.649150,-2.957923,-1.918378,...,1.918378,8.042944,1.377033,10.895641,3.851816,0.429135,8.652654,20.573937,NaN,NaN

# 4. Save the data

In [5]:
import pandas as pd
feature_df.to_csv("./data/angela_final.csv")